### PR TITLE
monorepo warning

### PR DESCRIPTION
**Pull request by the-right-joyce**

### CODE REVIEW

**Review by jonnysmillie — CHANGES_REQUESTED** [review]
Please make sure the previous banner message (in this case sub0) has 'active' set to false too before an update is merged :)

There should only be one banner active at any time.

**Comment by the-right-joyce** [comment]
hey @jonnysmillie do you know long do we want to keep the sub0 banner active? Is it still relevant for marketing? We would like to have this one only for 2 weeks active (1 before and 1 after the merge)

**Comment by jonnysmillie** [comment]
Hello @the-right-joyce I think it is still relevant but let me check. I can see why your banner might take precedence though. Which 2 weeks does yours need to be live?

**Comment by the-right-joyce** [comment]
from Aug 18th until Sep 1st

**Pull request closed without merging**
