### PR TITLE
Add a banner about Polkadot SDK

### PR DESCRIPTION
**Pull request by rzadp**
Addresses [this](https://github.com/polkadot-developers/substrate-docs/pull/2172#issuecomment-2315642856).

Screenshot 2024-09-03 at 13 20 38

### CODE REVIEW

**Review by mordamax — APPROVED** [review]

**Comment by kianenigma** [comment]
Amaizng 🚀

**Review by kianenigma — APPROVED** [review]

**Comment by kianenigma** [comment]
Okay, sorry, maybe I should have not merged this -- not sure if there is an automatic CI to now build the website with it?

**Comment by kianenigma** [comment]
We need to trigger a re-build of https://github.com/paritytech/substrate-website?

**Comment by rzadp** [comment]
> We need to trigger a re-build of https://github.com/paritytech/substrate-website?

No, it is loaded dynamically on client-side.

For me, it already appears on https://substrate.io/

**Pull request merged**
